In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [10]:
x = torch.empty(5, 3)
# print(x)

Construct a randomly initialized matrix:



In [11]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.2215,  0.0465,  0.8946],
        [ 0.4975,  0.4405,  0.4621],
        [ 0.0123,  0.0209,  0.6708],
        [ 0.3221,  0.4385,  0.1329],
        [ 0.7582,  0.0899,  0.5506]])


Construct a matrix filled zeros and of dtype long:



In [12]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a tensor directly from data:



In [13]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [14]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.4401,  0.7376, -0.0605],
        [-1.5592,  0.4219, -0.4098],
        [-0.7483, -2.2282,  0.5209],
        [-1.2960, -0.1534,  1.4570],
        [ 0.2481, -0.6188,  0.3109]])


Get its size:



In [15]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4624,  1.1929,  0.9060],
        [-0.9890,  1.1726,  0.2421],
        [-0.6666, -1.6589,  0.8211],
        [-0.9641, -0.0203,  2.3124],
        [ 0.4213,  0.0290,  0.7650]])


Addition: syntax 2



In [17]:
print(torch.add(x, y))

tensor([[ 0.4624,  1.1929,  0.9060],
        [-0.9890,  1.1726,  0.2421],
        [-0.6666, -1.6589,  0.8211],
        [-0.9641, -0.0203,  2.3124],
        [ 0.4213,  0.0290,  0.7650]])


Addition: providing an output tensor as argument



In [18]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4624,  1.1929,  0.9060],
        [-0.9890,  1.1726,  0.2421],
        [-0.6666, -1.6589,  0.8211],
        [-0.9641, -0.0203,  2.3124],
        [ 0.4213,  0.0290,  0.7650]])


Addition: in-place



In [19]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.4624,  1.1929,  0.9060],
        [-0.9890,  1.1726,  0.2421],
        [-0.6666, -1.6589,  0.8211],
        [-0.9641, -0.0203,  2.3124],
        [ 0.4213,  0.0290,  0.7650]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [20]:
print(x[:, 1])

tensor([ 0.7376,  0.4219, -2.2282, -0.1534, -0.6188])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [22]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print('x:', x.size(), ', y:', y.size(), 'z:', z.size())

x: torch.Size([4, 4]) , y: torch.Size([16]) z: torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [23]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 2.1305])
2.130511999130249


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array



In [24]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [26]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# # let us run this cell only if CUDA is available
# # We will use ``torch.device`` objects to move tensors in and out of GPU
# if torch.cuda.is_available():
#     device = torch.device("cuda")          # a CUDA device object
#     y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
#     x = x.to(device)                       # or just use strings ``.to("cuda")``
#     z = x + y
#     print(z)
#     print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!